version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rails_app
    command:
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres

  db:
    image: postgres:latest
    container_name: postgres_db
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

volumes:
  db_data:
